[general]
title = "Default configuration for the NARPS open pipelines project"
config_type = "default"

[directories]
dataset = "data/original/ds001734/"
reproduced_results = "data/reproduced/"
narps_results = "data/results/"
