[general]
title = "Testing configuration for the NARPS open pipelines project"
config_type = "testing"

[directories]
dataset = ""
reproduced_results = ""
narps_results = "data/narps_results"
test_data = "tests/test_data/"
