## Disclaimer - This GitHub Actions workflow runs all the changed tests for the project.

# Name the workflow
name: test_changes

# Define when it runs (on PR when a test changes)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'tests/**'

# Jobs that define the workflow
jobs:

  # A job to list the tests to be run
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch for comparison
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Checkout current branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Create a list of tests for changed tests
      id: identify
      run: |
        echo "tests=$(git diff --name-only remotes/origin/main...$GITHUB_SHA)" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Collect tests with pytest
      run: pytest --collect-only -q ${{ steps.identify.outputs.tests }}
