## Disclaimer - This GitHub Actions workflow runs all the unit tests for the project.

# Name the workflow
name: unit_testing

# Define when it runs (on pushes when narps_open files change)
on:
  workflow_dispatch:
  push:
    paths:
      - 'narps_open/**'

# Jobs that define the workflow
jobs:
  # Name of the job running unit tests
  pytest:

    # Define the runner for this job
    runs-on: ubuntu-latest

    # Steps that define the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Launch tests with pytest & get code coverage
      run: |
        coverage run -m pytest --junit-xml=pytest_report.xml -m "not pipeline_test"
        coverage report
        coverage xml

    - name: Archive pytest results
      uses: actions/upload-artifact@v3
      with:
        name: unit_tests-reports
        path: |
          pytest_report.xml
          coverage.xml
        retention-days: 15
